name: utility
description: Utility helps developers to use dart more easily and effeciently.
version: 1.0.2
homepage: https://github.com/justkawal/utility.git

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  test: ^1.21.4
  flutter_lints: ^2.0.1