name: utility
description: Utility helps developers to use dart more easily and effeciently.
version: 1.0.1-nullsafety.1
homepage: https://github.com/justkawal/utility.git

environment:
  sdk: '>=2.12.0-133.7.beta <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.15
